updated from mod template
1.20 support
6ac4aeca1ca90df52e7f456b8091304baabd4fed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,6 +18,17 @@ on:
 
 
 jobs:
+  show_action_parameters:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Show action parameters
+        run: |
+          cat <<EOF > $GITHUB_STEP_SUMMARY
+          ## Action Parameters
+          - target_subproject: `${{ github.event.inputs.target_subproject }}`
+          - target_release_tag: `${{ github.event.inputs.target_release_tag }}`
+          EOF
+
   matrix_prep:
     uses: ./.github/workflows/matrix_prep.yml
     with:
@@ -26,6 +37,7 @@ jobs:
   build:
     uses: ./.github/workflows/build.yml
     with:
+      target_subproject: ${{ github.event.inputs.target_subproject }}
       release: true
 
   release:
@@ -34,11 +46,16 @@ jobs:
       - build
     runs-on: ubuntu-latest
 
+    # allow the mod publish step to add asserts to release
+    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+    permissions:
+      contents: write
+
     strategy:
-      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
+      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
       - name: Download build artifacts
         uses: actions/download-artifact@v3
@@ -49,42 +66,69 @@ jobs:
       - name: Get github release information
         if: ${{ github.event_name == 'workflow_dispatch' }}
         id: get_release
-        uses: cardinalby/git-get-release-action@v1.1
+        uses: cardinalby/git-get-release-action@1.2.4
         env:
           GITHUB_TOKEN: ${{ github.token }}
         with:
           tag: ${{ github.event.inputs.target_release_tag }}
 
-      - name: Generate publish related infomation
+      - name: Generate publish related information
         id: release_info
         run: |
           if [ $GITHUB_EVENT_NAME == 'release' ]
           then
-              echo "::set-output name=tag_name::"  # leave an empty value here so softprops/action-gh-release will use the default value
+              echo "tag_name=" >> $GITHUB_OUTPUT  # leave an empty value here so softprops/action-gh-release will use the default value
           elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
           then
-              echo "::set-output name=tag_name::${{ github.event.inputs.target_release_tag }}"
+              echo "tag_name=${{ github.event.inputs.target_release_tag }}" >> $GITHUB_OUTPUT
           else
               echo Unknown github event name $GITHUB_EVENT_NAME
               exit 1
           fi
 
-      - name: Read Properties mod_version
-        id: mod_version
-        uses: christian-draeger/read-properties@1.0.1
+      - name: Read common properties
+        id: properties_g
+        uses: christian-draeger/read-properties@1.1.1
         with:
           path: gradle.properties
-          property: mod_version
+          properties: 'mod_name mod_version'
 
-      - name: Read Properties minecraft_version
-        id: minecraft_version
-        uses: christian-draeger/read-properties@1.0.1
+      - name: Read version-specific properties
+        id: properties_v
+        uses: christian-draeger/read-properties@1.1.1
         with:
           path: ${{ format('versions/{0}/gradle.properties', matrix.subproject_dir) }}
-          property: minecraft_version
+          properties: 'minecraft_version game_versions'
+
+      - name: Fix game version
+        id: game_versions
+        run: |
+          # Fixed \n in game_versions isn't parsed by christian-draeger/read-properties as a line separator
+          echo 'value<<EOF' >> $GITHUB_OUTPUT
+          echo -e "${{ steps.properties_v.outputs.game_versions }}" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+
+      - name: Prepare file information
+        id: file_info
+        run: |
+          shopt -s extglob
+          FILE_PATHS=$(ls ${{ format('build-artifacts/{0}/build/libs/!(*-@(dev|sources)).jar', matrix.subproject_dir) }})
+          if (( ${#FILE_PATHS[@]} != 1 )); then
+              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
+              exit 1
+          else
+              FILE_PATH=${FILE_PATHS[0]}
+          fi
+          
+          FILE_NAME=$(basename $FILE_PATH)
+          FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
+          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
+          echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
+          echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
 
       - name: Publish Minecraft Mods
-        uses: Kir-Antipov/mc-publish@v2.1
+        uses: Kir-Antipov/mc-publish@v3.2
         with:
           modrinth-id: HCbarMw6
           modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}
@@ -95,16 +139,25 @@ jobs:
           github-tag: ${{ steps.release_info.outputs.tag_name }}
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-          files-primary: ${{ format('build-artifacts/{0}/build/libs/!(*-@(dev|sources)).jar', matrix.subproject_dir) }}
+          files-primary: ${{ steps.file_info.outputs.path }}
           files-secondary: ''
 
-          name: ${{ format('Litematica Server Paster v{0} for mc{1}', steps.mod_version.outputs.value, steps.minecraft_version.outputs.value) }}
-          version: ${{ format('mc{0}-v{1}', steps.minecraft_version.outputs.value, steps.mod_version.outputs.value) }}
+          name: ${{ format('{0} v{1} for mc{2}', steps.properties_g.outputs.mod_name, steps.properties_g.outputs.mod_version, steps.properties_v.outputs.minecraft_version) }}
+          version: ${{ format('mc{0}-v{1}', steps.properties_v.outputs.minecraft_version, steps.properties_g.outputs.mod_version) }}
           version-type: release
-          changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}  # one of them should be an empty string (null)
+          changelog: |-
+            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+            
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
           loaders: fabric
-          game-versions: ${{ matrix.game_versions }}
+          game-versions: ${{ steps.game_versions.outputs.value }}
           dependencies: 'litematica | depends'
           version-resolver: exact
 
